name: code check on pull requests

on:
  pull_request:
  # refs https://github.com/ArtiomTr/jest-coverage-report-action#forks-with-no-write-permission
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  code-check:
    runs-on: ubuntu-latest
    name: Code check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0
          cache: npm
      - run: npm install
      - run: npm run build -- --log-prefix=none
      - run: npm run lint
      - name: Type Check
        run: npm run type-check -- --log-prefix=none
