name: code check on pull requests

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # refs https://azukiazusa.dev/blog/monorepo-github-actions-jest-coverage-report-action/
  get-changed-workspaces:
    name: Get changed packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changed-packages.outputs.packages }}
      empty: ${{ steps.changed-packages.outputs.empty }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Find changed packages
        uses: alexshukel/get-changed-workspaces-action@e1b6faa54b788d9093c8bf234368859f1bcbb2b3 # v2.0.0
        id: changed-packages
        with:
          workspaces: |
            apps/*

  coverage:
    name: Coverage report
    # このジョブを実行するためには get-changed-workspaces が正常に完了している必要がある
    needs: [get-changed-workspaces]
    if: ${{ !fromJson(needs.get-changed-workspaces.outputs.empty) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 変更された packages をマトリックス戦略に渡す
        package: ${{ fromJson(needs.get-changed-workspaces.outputs.packages) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24.14.1
          cache: npm
      - name: "Install"
        run: npm install
      - name: "Test"
        working-directory: apps/${{ matrix.package.name }}
        run: npm run test:ci
      - uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # ワークフローを実行するディレクトリを指定する
          working-directory: apps/${{ matrix.package.name }}
